MYSQL_HOST=localhost
MYSQL_DB=testdb
MYSQL_USER=c
MYSQL_PASSWORD=password
MYSQL_NCONS=10
B_NTHREADS=100
B_PORT=8888

CLUSTER_MODE=true
#CLUSTER_MODE=false
# the address of the cluster manager
CLUSTER_IP=10.114.0.4
CLUSTER_PORT=8889
